name: Bump version

on:
    pull_request:
        types:
            - closed
    push:
        branches:
            - master
    issue_comment:
        types: [created]
    workflow_dispatch:

env:
    BOT_PR_BRANCH: version-bump
    BOT_PR_TITLE: "Bump version"
    BOT_REFERENCE_BRANCH: master
    BOT_COMMAND_PREFIX: "@versionbot"

jobs:
    update:
        name: Create or update PR
        if:
            github.event_name == 'push' || github.event_name == 'workflow_dispatch' || ( github.event_name == 'pull_request' && github.event.pull_request.title=='Bump version' ) || ( github.event_name == 'issue_comment' && github.event.issue.title=='Bump version' )
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ env.BOT_REFERENCE_BRANCH }}

            - name: Update version in package.json ✏️
              run: |
                  npm version --no-git-tag-version patch
              working-directory: ./
              
            - name: Update version in package.json ✏️
              run: |
                  npm version --no-git-tag-version minor
              working-directory: ./
              if: 
                  contains(github.event.comment.body, 'versionbot') && contains(github.event.comment.body, 'minor')

            - name: Update version in package.json ✏️
              run: |
                  npm version --no-git-tag-version major
              working-directory: ./
              if: 
                  contains(github.event.comment.body, 'versionbot') && contains(github.event.comment.body, 'major')

            - name: Create Pull Request 📤
              uses: peter-evans/create-pull-request@v4
              with:
                  base: ${{ env.BOT_REFERENCE_BRANCH }}
                  branch: ${{ env.BOT_PR_BRANCH }}
                  title: ${{ env.BOT_PR_TITLE }}
